### ISSUE TITLE
Unexpected behavior

### ISSUE THREAD

**Issue by bree7e** [SaifurRahmanMohsin/oc-rest-plugin#11]
Initial conditions:
1. clean install. build 433. theme: Responsiv.Clean
2. install RESTful plugin
3. scaffolding
```
php artisan create:restcontroller Rainlab.Blog Posts
RESTful Controller created successfully.
```
4. ~\plugins\rainlab\blog\http\posts\config_rest.yaml
```
# ===================================
#  Rest Behavior Config
# ===================================

# Allowed Rest Actions
allowedActions:
  index:
      pageSize: 20
  show:

# Model Class name
modelClass: Rainlab\Blog\Models\Post
```
---
It is expected  only index and show actions are allowed.  
But if i send PUT, DELETE or POST request, it will be executed

For example
```http
DELETE http://api-test.loc/api/v1/posts/1 HTTP/1.1
```
Response
```
HTTP/1.1 200 OK
Date: Sat, 17 Feb 2018 10:22:57 GMT
Content-Type: application/json
Content-Length: 1052
Connection: keep-alive
Keep-Alive: timeout=60
Server: Apache
Cache-Control: private, must-revalidate
pragma: no-cache
expires: -1

{
  "id": 1,
  "user_id": null,
  "title": "First blog post",
  "slug": "first-blog-post",
  "excerpt": "The first ever blog post is here. It might be a good idea to update this post with some more relevant content.",
  "content": "This is your first ever **blog post**! It might be a good idea to update this post with some more relevant content.\n\nYou can edit this content by selecting **Blog** from the administration back-end menu.\n\n*Enjoy the good times!*",
  "content_html": "<p>This is your first ever <strong>blog post</strong>! It might be a good idea to update this post with some more relevant content.</p>\n<p>You can edit this content by selecting <strong>Blog</strong> from the administration back-end menu.</p>\n<p><em>Enjoy the good times!</em></p>",
  "published_at": "2018-02-17 10:20:56",
  "published": 1,
  "created_at": "2018-02-17 10:20:56",
  "updated_at": "2018-02-17 10:20:56",
  "summary": "The first ever blog post is here. It might be a good idea to update this post with some more relevant content.",
  "has_summary": true,
  "featured_images": [],
  "content_images": []
}
```
